# Netlify configuration file

# Build settings
[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio", "@supabase/supabase-js", "@google/generative-ai"]
  node_version = "18"

# Redirects and headers
[[redirects]]
  # Redirect all paths to index.html with a 200 status code
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML and JSON
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"